# build-time configuration; everything runtime (vault url, authentication, renew-grace-period,
# jdbc url, credentials provider role) is provided by the test resources
quarkus.datasource.db-kind=postgresql
quarkus.datasource.credentials-provider=reproducer
quarkus.vault.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.vault.log-confidentiality-level=low
quarkus.log.category."io.quarkus.vault".min-level=DEBUG
quarkus.log.category."io.quarkus.vault".level=DEBUG
